export const PEOPLE = [
  {
    firstName: "Michael",
    lastName: "Jones",
    email: "michael.jones@acmetravels.com",
    profession: "CTO Acme Travels",
    membership: "VIP",
  },
  {
    firstName: "firstName",
    lastName: "lastName",
    email: "email@email.com",
    profession: "profession",
    membership: "membership",
  },
  {
    firstName: "firstName",
    lastName: "lastName",
    email: "email@email.com",
    profession: "profession",
    membership: "membership",
  },
  {
    firstName: "firstName",
    lastName: "lastName",
    email: "email@email.com",
    profession: "profession",
    membership: "membership",
  },
  {
    firstName: "firstName",
    lastName: "lastName",
    email: "email@email.com",
    profession: "profession",
    membership: "membership",
  },
  {
    firstName: "firstName",
    lastName: "lastName",
    email: "email@email.com",
    profession: "profession",
    membership: "membership",
  },
  {
    firstName: "firstName",
    lastName: "lastName",
    email: "email@email.com",
    profession: "profession",
    membership: "membership",
  },
  {
    firstName: "firstName",
    lastName: "lastName",
    email: "email@email.com",
    profession: "profession",
    membership: "membership",
  },
  {
    firstName: "firstName",
    lastName: "lastName",
    email: "email@email.com",
    profession: "profession",
    membership: "membership",
  },
  {
    firstName: "firstName",
    lastName: "lastName",
    email: "email@email.com",
    profession: "profession",
    membership: "membership",
  },
  {
    firstName: "firstName",
    lastName: "lastName",
    email: "email@email.com",
    profession: "profession",
    membership: "membership",
  },
  {
    firstName: "firstName",
    lastName: "lastName",
    email: "email@email.com",
    profession: "profession",
    membership: "membership",
  },
  {
    firstName: "firstName",
    lastName: "lastName",
    email: "email@email.com",
    profession: "profession",
    membership: "membership",
  },
  {
    firstName: "firstName",
    lastName: "lastName",
    email: "email@email.com",
    profession: "profession",
    membership: "membership",
  },
  {
    firstName: "firstName",
    lastName: "lastName",
    email: "email@email.com",
    profession: "profession",
    membership: "membership",
  },
];
